#!/usr/bin/env python

import os
import sys

if __name__ == "__main__":
    sys.path.append(os.path.join(os.path.join(os.getcwd(), os.path.dirname(__file__)), '..'))
    from fhirtordf.fhirtordf import fhirtordf
    fhirtordf(sys.argv[1:])
